In [46]:
import pandas as pd
import numpy as np

# Sample Python dictionary data and list labels:

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# 第十六題
## Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

Sort the data frame first by 'name' in descending order, then by 'score' in ascending order:
name score attempts qualify
a Anastasia 12.5 1 yes
b Dima 9.0 3 no
c Katherine 16.5 2 yes
d James NaN 3 no
e Emily 9.0 2 no
f Michael 20.0 3 yes
g Matthew 14.5 1 yes
h Laura NaN 1 no
i Kevin 8.0 2 no
j Jonas 19.0 1 yes

In [7]:
df = pd.DataFrame(exam_data, index = labels)

df.sort_values(['name','score'],ascending = [False,True])


name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

# 第十七題
## Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

Replace the 'qualify' column contains the values 'yes' and 'no' with T
rue and False:
attempts name qualify score
a 1 Anastasia True 12.5
b 3 Dima False 9.0
......
i 2 Kevin False 8.0
j 1 Jonas True 19.0

### 寫法1

In [17]:
df = pd.DataFrame(exam_data, index = labels)

df['qualify'] = df['qualify'].replace('yes',True).replace('no',False)
print(df)

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


### 寫法2

### 對於map來說，它做的事情就是"將原本的值映射(mapping)到另外的值"
### 因此map不但可以接收一個函數，它也可以接受dictionary或另外一個Series
### 只要是可以一一對應的就好


In [18]:
df = pd.DataFrame(exam_data, index = labels)

df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
print(df)

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


# 第十八題
## Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

Expected Output:
Change the name 'James' to \?Suresh\?:
attempts name qualify score
a 1 Anastasia yes 12.5
b 3 Dima no 9.0
.......
i 2 Kevin no 8.0
j 1 Jonas yes 19.0

In [21]:
df = pd.DataFrame(exam_data, index = labels)

df['name'] = df['name'].replace('James','Suresh')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# 第十九題
## Write a Pandas program to delete the 'attempts' column from the DataFrame.

Expected Output:
Delete the 'attempts' column from the data frame:
name qualify score
a Anastasia yes 12.5
b Dima no 9.0
.....
i Kevin no 8.0
j Jonas yes 19.0

### 寫法1

In [29]:
df = pd.DataFrame(exam_data, index = labels)

df.drop(columns='attempts')

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

### 寫法2

In [33]:
df2 = pd.DataFrame(exam_data, index = labels)

df2.pop('attempts')
print(df2)

        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes


# 第二十題
## Write a Pandas program to insert a new column in existing DataFrame.

Expected Output:
New DataFrame after inserting the 'color' column
attempts name qualify score color
a 1 Anastasia yes 12.5 Red
b 3 Dima no 9.0 Blue
.......
i 2 Kevin no 8.0 Green
j 1 Jonas yes 19.0 Red

In [34]:
df = pd.DataFrame(exam_data, index = labels)

df['color'] = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red']
print(df)

        name  score  attempts qualify   color
a  Anastasia   12.5         1     yes     Red
b       Dima    9.0         3      no    Blue
c  Katherine   16.5         2     yes  Orange
d      James    NaN         3      no     Red
e      Emily    9.0         2      no   White
f    Michael   20.0         3     yes   White
g    Matthew   14.5         1     yes    Blue
h      Laura    NaN         1      no   Green
i      Kevin    8.0         2      no   Green
j      Jonas   19.0         1     yes     Red


# 第二十一題
## Write a Pandas program to iterate over rows in a DataFrame.

Sample Python dictionary data and list labels:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]

Expected Output:
Anastasia 12.5
Dima 9.0
Katherine 16.5

In [45]:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
df = pd.DataFrame(exam_data)

# 这里的iterrows()返回值为元组,(index,row)
for index, row in df.iterrows():
    print(row['name'],row['score'])





Anastasia 12.5
Dima 9.0
Katherine 16.5


# 第二十二題
## Write a Pandas program to get list from DataFrame column headers. 

Expected Output:
['attempts', 'name', 'qualify', 'score']

In [57]:
df = pd.DataFrame(exam_data, index = labels)

print(list(df.columns.values))


['name', 'score', 'attempts', 'qualify']


# 第二十三題
## Write a Pandas program to rename columns of a given DataFrame

Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 9


New DataFrame after renaming columns:
Column1 Column2 Column3
0 1 4 7
1 2 5 8
2 3 6 9

### 寫法1

In [59]:
example = {"col1":[1,2,3],"col2":[4,5,6], 'col3':[7,8,9]}

df1 = pd.DataFrame(example)
df1.rename(columns={'col1':'Column1','col2':'Column2','col3':'Column3'})

Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9

### 寫法2

In [62]:
example = {"col1":[1,2,3],"col2":[4,5,6], 'col3':[7,8,9]}

df1 = pd.DataFrame(example)

df1.columns = ['Column1','Column2', 'Column3']
print(df1)


   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9


# 第二十四題
##  Write a Pandas program to select rows from a given DataFrame based on values in some columns.

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1


Rows for colum1 value == 4
col1 col2 col3
1 4 5 8
3 4 7 0

### 寫法1

In [80]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}

df = pd.DataFrame(example)

print(df.query('col1 == 4'))

   col1  col2  col3
1     4     5     8
3     4     7     0


### 寫法2

In [ ]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}

df = pd.DataFrame(example)

print(df.loc[df['col1'] == 4])

# 第二十五題
## Write a Pandas program to change the order of a DataFrame columns.

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1

After altering col1 and col3
col3 col2 col1
0 7 4 1
1 8 5 4
2 9 6 3
3 0 7 4
4 1 8 5

In [81]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}

df = pd.DataFrame(example)

df = df[['col3','col2','col1']]
print(df)

   col3  col2  col1
0     7     4     1
1     8     5     4
2     9     6     3
3     0     7     4
4     1     8     5


# 第二十六題
## Write a Pandas program to add one row in an existing DataFrame.

After add one row:
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1
5 10 11 12

In [86]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}

df = pd.DataFrame(example)

df.loc[5] = [10,11,12]
print(df)

   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


# 第二十七題
## Write a Pandas program to write a DataFrame to CSV file using tab separator.

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1

Data from new_file.csv file:
col1\tcol2\tcol3
0 1\t4\t7
1 4\t5\t8
2 3\t6\t9
3 4\t7\t0
4 5\t8\t1

In [91]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}
df = pd.DataFrame(example)

df.to_csv('new_file.csv', sep = '\t', index = False)

df1 = pd.read_csv('new_file.csv')
print(df1)




  col1\tcol2\tcol3
0          1\t4\t7
1          4\t5\t8
2          3\t6\t9
3          4\t7\t0
4          5\t8\t1


# 第二十八題
## Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).

Sample data:
    city      Number of people
0 California        4
1 Georgia           2
2 Los Angeles       4

In [102]:
df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})

#print(df1)

g1 = df1.groupby('city').size().reset_index(name='Number of people')
print(g1)





          city  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4


# 第二十九題
## Write a Pandas program to delete DataFrame row(s) based on given column value

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1

New DataFrame
col1 col2 col3
0 1 4 7
2 3 6 9
3 4 7 0
4 5 8 1

In [110]:
example = {"col1":[1,4,3,4,5],"col2":[4,5,6,7,8], 'col3':[7,8,9,0,1]}

df = pd.DataFrame(example)

df = df[df.col2 != 5]
print(df)

   col1  col2  col3
0     1     4     7
2     3     6     9
3     4     7     0
4     5     8     1


# 第三十題
## Write a Pandas program to widen output display to see more columns.

Sample data:
Original DataFrame
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1

In [111]:
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

df = pd.DataFrame(data=d)

pd.set_option('display.max_rows', 500)

pd.set_option('display.max_columns', 500)

pd.set_option('display.width', 1000)

print(df)

   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
